### ISSUE TITLE
layout issues

### ISSUE THREAD

**Issue by sneg55** [sneg55/defiprime#14]
1. Fix About author block (check figma design: https://www.figma.com/file/f3nnSXBLnF0iPofxtWjicJ1X/Defiprime.com?node-id=58%3A2 )
![image](https://user-images.githubusercontent.com/7769371/58439665-12288b80-808a-11e9-94c2-68bbcdbd96a8.png)

2. Fix inactive links at "Read more" (blog)

3. Fix top menu spacing when more than 1 link used at the menu: 
![image](https://user-images.githubusercontent.com/7769371/58439728-8e22d380-808a-11e9-810b-74fbc77f2258.png)

**Comment by dianatashlanova** [comment]
@sneg55 непонятно, что за ссылка Read more и что нужно исправить
