### ISSUE TITLE
New project listing: MARKET Protocol

### ISSUE THREAD

**Issue by BassBauman** [sneg55/defiprime#20]
Name: MARKET Protocol

Type: Derivatives

Summary: MARKET Protocol is a framework for creating tokens that track prices of traditional or digital assets, providing financial access to anyone anywhere.

Website: https://marketprotocol.io/

**Comment by sneg55** [comment]
claimed: **access to anyone anywhere**  

but in fact: 

![image](https://user-images.githubusercontent.com/7769371/59954624-857bae00-943a-11e9-878d-b9bdd0b519b5.png)

**Comment by BassBauman** [comment]
Please tell me what information you're looking for. I gave a mission statement, do you want a description instead?

We are working on making access available in the U.S. but it will take more time. It's a regulatory limitation, not a technical one.

Rather than waiting, we chose an international launch first, as have many other DeFi projects.

**Comment by sneg55** [comment]
We measured community sentiment on regional restrictions before: https://twitter.com/defiprime/status/1130890433821724672 

I don't think that MARKET Protocol fits well for listing on defiprime.com with existing geo-restrictions.

**Comment by BassBauman** [comment]
The geo-restriction applies to our frontend only. Position Tokens themselves are ERC-20 assets, so we don't and can't control what traders choose to do with them off of our DEX.

I hope you will reconsider, for the sake of all the teams out there who are building important tech while also navigating an [uncertain regulatory environment](https://www.theblockcrypto.com/tiny/bancor-is-cutting-off-us-users-from-trading-on-its-dex/).

**Comment by sneg55** [comment]
So why there is no geo-restrictions on dydx, fullcrum, synth, opyn, set? Not so uncertain for them or they willing to take risks?

**Comment by BassBauman** [comment]
A combination. Most of those projects operate margin applications, which generally aren't an issue. The synthetic asset projects take the position that the user is responsible for complying with applicable law.

DeFi teams are walking a tightrope between lawyers and regulators, while also building world changing technology. Each project is different, depending on its focus, implementation, and location, but ultimately every DeFi team makes a decision based on the particular regulatory uncertainty they are facing and the risk they're willing to take. Do you really think you can judge?

**Comment by sneg55** [comment]
Thanks for the clarification, I listed Market Protocol here: https://defiprime.com/infrastructure
