### ISSUE TITLE
Graychain/Grayscore

### ISSUE THREAD

**Issue by mostar93** [sneg55/defiprime#22]
We offer credit scoring based upon defi lending activity. Currently we are measuring users reliability based upon the number of open loans, loan history, credit utilization vs collateralized capital and payment history. Check out our live demo at:

https://app.grayscore.io/

Enter the address and hit enter. Upon completion, the address will be given a score from 1 - 1000 as well as which lending platforms they currently have open loans with.

Currently we are scoring any addresses that have loans open with Maker DAO, DYDX and Compound with additional platforms coming soon.

Our goal is to reduce counter-party risk for lenders as well as allowing borrowers access to loans at lower LTV's.

Here is some info about our company:
https://graychain.net/about-us/

**Comment by sneg55** [comment]
Looks interesting, can you follow up when the public beta is live, and developers documentation is ready?

**Comment by mostar93** [comment]
For sure. Just wanted to get on your radar. Thanks!
