### ISSUE TITLE
Add location to DeFi solution providers

### ISSUE THREAD

**Issue by jamesmorgan** [sneg55/defiprime#26]
Sounds stupid to add in physical location to the decentralized finance curated site but this would be useful for a few reasons in my mind.

1) When organising events/meetups etc I often try to reach out to companies building but time is wasted when they are not geographically close enough to come and attend/talk - having this info would be super useful. 

2) To allow easy viewing of different jurisdictions so users understand if there are rules or regulations which may impact the use of any products. 

Love the site and the list, this is just an idea I thought may ne useful. Also not sure how hard it would be to add and or collate.

**Comment by sneg55** [comment]
Thanks for the idea! However, I can't see right now how to make it. Many DeFi teams are remote-first, and even more doesn't disclosure jurisdictions or HQ location.
