### ISSUE TITLE
Update ETHLend information in Decentralized Lending section

### ISSUE THREAD

**Issue by sirsoth** [sneg55/defiprime#7]
Hello,

Congratulations for your great site! We would like to update the information of ETHLend, is it possible to add the Bitcoin icon as we allow BTC usage as collateral in a non-custodial way (using multisig wallets) and also we would like to update our description to:

"ETHLend is a decentralized peer to peer lending marketplace. Users can put a loan request or a loan offer choosing their preferred conditions and the platform allows them to match. Everything is regulated through Smart Contracts."

If you need confirmation from my side you can also contact me at pablo@ethlend.io 

Best regards,
Pablo Candela.

**Comment by sneg55** [comment]
Thanks! 

I've updated ETHLend description here: https://defiprime.com/decentralized_lending

**Comment by sirsoth** [comment]
Thank you so much @sneg55 !

**Comment by sneg55** [comment]
You are welcome, retweets appreciated! @sirsoth

**Comment by sirsoth** [comment]
For sure!
